dict = dict(logUrl=r'C:\Users\akshat.gupta\PycharmProjects\\atlas\\mysite\\atlas\\PyScripts\\Outputs\Log\\',
            outputUrl=r'C:\Users\akshat.gupta\PycharmProjects\atlas\\mysite\\atlas\\database\\ATLAS_Universal_2.csv',
            outputPath=r'C:\Users\akshat.gupta\PycharmProjects\\mysite\\atlas\\database\\Outputs\\',
            requestUrl=r'C:\Users\akshat.gupta\PycharmProjects\\atlas\\mysite\\atlas\\database\\request.csv',
            requestUrl1=r'..\\atlas\\database\\request.csv',

            amazonOutput=r'C:\Users\akshat.gupta\PycharmProjects\\atlas\\mysite\\atlas\\PyScripts\\Outputs\\Amazon_I\\',
            homedepotOutput='C:\Users\akshat.gupta\PycharmProjects\\atlas\\mysite\\atlas\\PyScripts\\Outputs\\HomeDepot\\',
            chromeDriver=r'C:\Users\akshat.gupta\PycharmProjects\\atlas\\mysite\\atlas\\chromedriver.exe',
            keywordsDict=r'C:\Users\akshat.gupta\PycharmProjects\\atlas\\mysite\\atlas\\database\\keywordsSubTD.csv',
            #tagDict=r'C:\Users\akshat.gupta\PycharmProjects\\atlas\\mysite\\atlas\\database\\TaggingDicts\\TaggingDict.csv',
            tagDictPath=r'C:\Users\akshat.gupta\PycharmProjects\\atlas\\mysite\\atlas\\database\\TaggingDicts\\',
            tdDictsPath=r'C:\Users\akshat.gupta\PycharmProjects\\atlas\\mysite\\atlas\\database\\TrigDrivDicts\\',
            tri_dri_Output=r'C:\Users\akshat.gupta\PycharmProjects\\atlas\\mysite\\atlas\\database\\Outputs\\Triggers-Drivers\\',
            sentDict=r'C:\Users\akshat.gupta\PycharmProjects\\atlas\\mysite\\atlas\\database\\AFINN-111.txt',
            sentDictsPath=r'C:\Users\akshat.gupta\PycharmProjects\\atlas\\mysite\\atlas\\database\\SentiDicts\\',
            uploadsUrl=r'C:\Users\akshat.gupta\PycharmProjects\\atlas\\mysite\\atlas\\database\\uploads\\',
            topicViz=r'C:\Users\akshat.gupta\PycharmProjects\\atlas\\mysite\\atlas\\templates\\atlas\\includes\\',
            topicModels=r'C:\Users\akshat.gupta\PycharmProjects\\atlas\\mysite\\atlas\\database\\topicmodel\\models\\',
            logosPath=r'C:\Users\akshat.gupta\PycharmProjects\\atlas\\mysite\\atlas\\static\\atlas\\images\\icons\\',
            sourcesUrl=r'C:\Users\akshat.gupta\PycharmProjects\\atlas\\mysite\\atlas\\database\\sourceMap.csv',
            dbfolderPath=r'C:\Users\akshat.gupta\PycharmProjects\\atlas\\mysite\\atlas\\database\\',
            associationInput = r'C:\\Users\\akshat.gupta\\PycharmProjects\\atlas\\mysite\\atlas\\database\\fashion_brands.csv',
            )
