# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 11:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('atlas', '0002_auto_20170529_1658'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentiment', models.CharField(max_length=20)),
                ('trigger', models.CharField(max_length=20)),
                ('driver', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('pid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('pCategory', models.CharField(max_length=30)),
                ('pBrand', models.CharField(max_length=30)),
                ('pDescr', models.TextField()),
                ('pImgSrc', models.TextField()),
                ('pModel', models.CharField(max_length=30)),
                ('pTitle', models.TextField()),
                ('pURL', models.TextField()),
                ('pPrice', models.CharField(max_length=10)),
                ('siteCode', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('rid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('rDate', models.DateField()),
                ('rRating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('rText', models.TextField()),
                ('rTitle', models.TextField()),
                ('rURL', models.TextField()),
                ('rUser', models.CharField(max_length=30)),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atlas.Product')),
            ],
        ),
        migrations.AddField(
            model_name='analysis',
            name='rid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atlas.Review'),
        ),
    ]
