# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 07:08
from __future__ import unicode_literals

from django.db import migrations
import django_unixdatetimefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0003_auto_20170529_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rDate',
            field=django_unixdatetimefield.fields.UnixDateTimeField(),
        ),
    ]
