# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0005_product_prating'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='sentiScore',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
            preserve_default=False,
        ),
    ]
