# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0006_analysis_sentiscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rDate2',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='driver',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='sentiScore',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='sentiment',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='trigger',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
