# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-22 07:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_unixdatetimefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0007_auto_20170605_1826'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uploads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rDate', django_unixdatetimefield.fields.UnixDateTimeField()),
                ('rDate2', models.DateField(blank=True, null=True)),
                ('rRating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('rText', models.TextField()),
                ('rTitle', models.TextField()),
                ('rURL', models.TextField()),
                ('rUser', models.CharField(max_length=30)),
                ('rid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atlas.Review')),
            ],
        ),
    ]
