# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-22 07:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_unixdatetimefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0010_auto_20180122_1248'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadAnalyses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentiment', models.CharField(blank=True, max_length=20, null=True)),
                ('sentiScore', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('trigger', models.CharField(blank=True, max_length=20, null=True)),
                ('driver', models.CharField(blank=True, max_length=20, null=True)),
                ('rid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atlas.Review')),
            ],
        ),
        migrations.CreateModel(
            name='Uploads',
            fields=[
                ('rid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('rDate', django_unixdatetimefield.fields.UnixDateTimeField()),
                ('rDate2', models.DateField(blank=True, null=True)),
                ('rRating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('rText', models.TextField()),
                ('rTitle', models.TextField()),
                ('rURL', models.TextField()),
                ('rUser', models.CharField(max_length=30)),
            ],
        ),
    ]
