# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-22 07:26
from __future__ import unicode_literals

from django.db import migrations, models
import django_unixdatetimefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0012_auto_20180122_1255'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uploads',
            fields=[
                ('rid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('rDate', django_unixdatetimefield.fields.UnixDateTimeField()),
                ('rDate2', models.DateField(blank=True, null=True)),
                ('rRating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('rText', models.TextField()),
                ('rTitle', models.TextField()),
                ('rURL', models.TextField()),
                ('rUser', models.CharField(max_length=30)),
            ],
        ),
    ]
