# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-22 07:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0013_uploads'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadAnalyses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentiment', models.CharField(blank=True, max_length=20, null=True)),
                ('sentiScore', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('trigger', models.CharField(blank=True, max_length=20, null=True)),
                ('driver', models.CharField(blank=True, max_length=20, null=True)),
                ('rid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atlas.Review')),
            ],
        ),
    ]
