# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-22 08:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0014_uploadanalyses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadanalyses',
            name='rid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atlas.Uploads'),
        ),
    ]
