# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-23 09:22
from __future__ import unicode_literals

from django.db import migrations, models
import django_unixdatetimefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0017_auto_20180122_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploads',
            name='pCategory',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='uploads',
            name='rDate',
            field=django_unixdatetimefield.fields.UnixDateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='uploads',
            name='rRating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='uploads',
            name='rTitle',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='uploads',
            name='rURL',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='uploads',
            name='rUser',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
