# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-14 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0019_auto_20180123_1635'),
    ]

    operations = [
        migrations.CreateModel(
            name='DimenMap',
            fields=[
                ('dict_id', models.AutoField(primary_key=True, serialize=False)),
                ('dict_filename', models.TextField()),
                ('dimension', models.TextField()),
                ('level1', models.TextField()),
                ('level2', models.TextField()),
                ('level3', models.TextField()),
                ('level4', models.TextField()),
                ('level5', models.TextField()),
            ],
        ),
    ]
