# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-15 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0020_dimenmap'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dimenmap',
            name='dict_id',
        ),
        migrations.RemoveField(
            model_name='dimenmap',
            name='dimension',
        ),
        migrations.RemoveField(
            model_name='dimenmap',
            name='level1',
        ),
        migrations.RemoveField(
            model_name='dimenmap',
            name='level2',
        ),
        migrations.RemoveField(
            model_name='dimenmap',
            name='level3',
        ),
        migrations.RemoveField(
            model_name='dimenmap',
            name='level4',
        ),
        migrations.RemoveField(
            model_name='dimenmap',
            name='level5',
        ),
        migrations.AddField(
            model_name='dimenmap',
            name='d10_l1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dimenmap',
            name='d10_l2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dimenmap',
            name='d10_l3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dimenmap',
            name='d10_l4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dimenmap',
            name='d10_l5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dimenmap',
            name='d11_l1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dimenmap',
            name='d11_l2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dimenmap',
            name='d11_l3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dimenmap',
            name='d11_l4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dimenmap',
            name='d11_l5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dimenmap',
            name='d12_l1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dimenmap',
            name='d12_l2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dimenmap',
            name='d12_l3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dimenmap',
            name='d12_l4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dimenmap',
            name='d12_l5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dimenmap',
            name='d13_l1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dimenmap',
            name='d13_l2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dimenmap',
            name='d13_l3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dimenmap',
            name='d13_l4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dimenmap',
            name='d13_l5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dimenmap',
            name='d14_l1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dimenmap',
            name='d14_l2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dimenmap',
            name='d14_l3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dimenmap',
            name='d14_l4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dimenmap',
            name='d14_l5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dimenmap',
            name='d15_l1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dimenmap',
            name='d15_l2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dimenmap',
            name='d15_l3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dimenmap',
            name='d15_l4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dimenmap',
            name='d15_l5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dimenmap',
            name='d1_l1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dimenmap',
            name='d1_l2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dimenmap',
            name='d1_l3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dimenmap',
            name='d1_l4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dimenmap',
            name='d1_l5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dimenmap',
            name='d2_l1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dimenmap',
            name='d2_l2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dimenmap',
            name='d2_l3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dimenmap',
            name='d2_l4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dimenmap',
            name='d2_l5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dimenmap',
            name='d3_l1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dimenmap',
            name='d3_l2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dimenmap',
            name='d3_l3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dimenmap',
            name='d3_l4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dimenmap',
            name='d3_l5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dimenmap',
            name='d4_l1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dimenmap',
            name='d4_l2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dimenmap',
            name='d4_l3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dimenmap',
            name='d4_l4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dimenmap',
            name='d4_l5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dimenmap',
            name='d5_l1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dimenmap',
            name='d5_l2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dimenmap',
            name='d5_l3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dimenmap',
            name='d5_l4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dimenmap',
            name='d5_l5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dimenmap',
            name='d6_l1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dimenmap',
            name='d6_l2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dimenmap',
            name='d6_l3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dimenmap',
            name='d6_l4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dimenmap',
            name='d6_l5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dimenmap',
            name='d7_l1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dimenmap',
            name='d7_l2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dimenmap',
            name='d7_l3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dimenmap',
            name='d7_l4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dimenmap',
            name='d7_l5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dimenmap',
            name='d8_l1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dimenmap',
            name='d8_l2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dimenmap',
            name='d8_l3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dimenmap',
            name='d8_l4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dimenmap',
            name='d8_l5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dimenmap',
            name='d9_l1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dimenmap',
            name='d9_l2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dimenmap',
            name='d9_l3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dimenmap',
            name='d9_l4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dimenmap',
            name='d9_l5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dimenmap',
            name='dim1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dimenmap',
            name='dim10',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dimenmap',
            name='dim11',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dimenmap',
            name='dim12',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dimenmap',
            name='dim13',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dimenmap',
            name='dim14',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dimenmap',
            name='dim15',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dimenmap',
            name='dim2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dimenmap',
            name='dim3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dimenmap',
            name='dim4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dimenmap',
            name='dim5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dimenmap',
            name='dim6',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dimenmap',
            name='dim7',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dimenmap',
            name='dim8',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dimenmap',
            name='dim9',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dimenmap',
            name='dict_filename',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
