# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-15 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0022_auto_20180515_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dimenmap',
            name='dict_id',
        ),
        migrations.AddField(
            model_name='dimenmap',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
