# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-16 07:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0027_auto_20180516_1307'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TagDicts',
        ),
    ]
