from __future__ import unicode_literals
from django.db import models
from django_unixdatetimefield import UnixDateTimeField


class Meta:
    app_label = 'atlas'


# Create your models here.
class Product(models.Model):
    pid = models.CharField(max_length=100, primary_key=True)
    pCategory = models.CharField(max_length=30)
    pBrand = models.CharField(max_length=30)
    pDescr = models.TextField()
    pRating = models.DecimalField(max_digits=2, decimal_places=1)
    pImgSrc = models.TextField()
    pModel = models.CharField(max_length=30)
    pTitle = models.TextField()
    pURL = models.TextField()
    pPrice = models.CharField(max_length=10)
    siteCode = models.CharField(max_length=2)

    def __unicode__(self):
        return unicode(self.pTitle)


class Review(models.Model):
    rid = models.CharField(max_length=100, primary_key=True)
    pid = models.ForeignKey(Product, on_delete=models.CASCADE)
    rDate = UnixDateTimeField()
    rDate2 = models.DateField(null=True, blank=True)
    rRating = models.DecimalField(max_digits=2, decimal_places=1)
    rText = models.TextField()
    rTitle = models.TextField()
    rURL = models.TextField()
    rUser = models.CharField(max_length=30)

    def __unicode__(self):
        return unicode(self.rTitle)


class Analysis(models.Model):
    rid = models.ForeignKey(Review, on_delete=models.CASCADE)
    sentiment = models.CharField(max_length=20, null=True, blank=True)
    sentiScore = models.DecimalField(max_digits=4, decimal_places=2,null=True, blank=True)
    trigger = models.CharField(max_length=200,null=True, blank=True)
    driver = models.CharField(max_length=200,null=True, blank=True)

    def __unicode__(self):
        return unicode(self.id)


class Uploads(models.Model):
    rid = models.CharField(max_length=100, primary_key=True)
    rDate = UnixDateTimeField(null=True, blank=True)
    rDate2 = models.DateField(null=True, blank=True)
    rRating = models.DecimalField(max_digits=2, decimal_places=1,null=True, blank=True)
    rText = models.TextField()
    rTitle = models.TextField(null=True, blank=True)
    rURL = models.TextField(null=True, blank=True)
    rUser = models.CharField(max_length=30,null=True, blank=True)
    pCategory = models.CharField(max_length=30,null=True, blank=True)

    def __unicode__(self):
        return unicode(self.rTitle)


class UploadAnalyses(models.Model):
    rid = models.ForeignKey(Uploads, on_delete=models.CASCADE)
    sentiment = models.CharField(max_length=20, null=True, blank=True)
    sentiScore = models.DecimalField(max_digits=4, decimal_places=2, null=True, blank=True)
    trigger = models.CharField(max_length=200, null=True, blank=True)
    driver = models.CharField(max_length=200, null=True, blank=True)

    def __unicode__(self):
        return unicode(self.id)


class DimenMap(models.Model):
    dict_filename = models.CharField(max_length=100)
    dim1 = models.TextField(null=True, blank=True)
    d1_l1 = models.TextField(null=True, blank=True)
    d1_l2 = models.TextField(null=True, blank=True)
    d1_l3 = models.TextField(null=True, blank=True)
    d1_l4 = models.TextField(null=True, blank=True)
    d1_l5 = models.TextField(null=True, blank=True)
    dim2 = models.TextField(null=True, blank=True)
    d2_l1 = models.TextField(null=True, blank=True)
    d2_l2 = models.TextField(null=True, blank=True)
    d2_l3 = models.TextField(null=True, blank=True)
    d2_l4 = models.TextField(null=True, blank=True)
    d2_l5 = models.TextField(null=True, blank=True)
    dim3 = models.TextField(null=True, blank=True)
    d3_l1 = models.TextField(null=True, blank=True)
    d3_l2 = models.TextField(null=True, blank=True)
    d3_l3 = models.TextField(null=True, blank=True)
    d3_l4 = models.TextField(null=True, blank=True)
    d3_l5 = models.TextField(null=True, blank=True)
    dim4 = models.TextField(null=True, blank=True)
    d4_l1 = models.TextField(null=True, blank=True)
    d4_l2 = models.TextField(null=True, blank=True)
    d4_l3 = models.TextField(null=True, blank=True)
    d4_l4 = models.TextField(null=True, blank=True)
    d4_l5 = models.TextField(null=True, blank=True)
    dim5 = models.TextField(null=True, blank=True)
    d5_l1 = models.TextField(null=True, blank=True)
    d5_l2 = models.TextField(null=True, blank=True)
    d5_l3 = models.TextField(null=True, blank=True)
    d5_l4 = models.TextField(null=True, blank=True)
    d5_l5 = models.TextField(null=True, blank=True)
    dim6 = models.TextField(null=True, blank=True)
    d6_l1 = models.TextField(null=True, blank=True)
    d6_l2 = models.TextField(null=True, blank=True)
    d6_l3 = models.TextField(null=True, blank=True)
    d6_l4 = models.TextField(null=True, blank=True)
    d6_l5 = models.TextField(null=True, blank=True)
    dim7 = models.TextField(null=True, blank=True)
    d7_l1 = models.TextField(null=True, blank=True)
    d7_l2 = models.TextField(null=True, blank=True)
    d7_l3 = models.TextField(null=True, blank=True)
    d7_l4 = models.TextField(null=True, blank=True)
    d7_l5 = models.TextField(null=True, blank=True)
    dim8 = models.TextField(null=True, blank=True)
    d8_l1 = models.TextField(null=True, blank=True)
    d8_l2 = models.TextField(null=True, blank=True)
    d8_l3 = models.TextField(null=True, blank=True)
    d8_l4 = models.TextField(null=True, blank=True)
    d8_l5 = models.TextField(null=True, blank=True)
    dim9 = models.TextField(null=True, blank=True)
    d9_l1 = models.TextField(null=True, blank=True)
    d9_l2 = models.TextField(null=True, blank=True)
    d9_l3 = models.TextField(null=True, blank=True)
    d9_l4 = models.TextField(null=True, blank=True)
    d9_l5 = models.TextField(null=True, blank=True)
    dim10 = models.TextField(null=True, blank=True)
    d10_l1 = models.TextField(null=True, blank=True)
    d10_l2 = models.TextField(null=True, blank=True)
    d10_l3 = models.TextField(null=True, blank=True)
    d10_l4 = models.TextField(null=True, blank=True)
    d10_l5 = models.TextField(null=True, blank=True)
    dim11 = models.TextField(null=True, blank=True)
    d11_l1 = models.TextField(null=True, blank=True)
    d11_l2 = models.TextField(null=True, blank=True)
    d11_l3 = models.TextField(null=True, blank=True)
    d11_l4 = models.TextField(null=True, blank=True)
    d11_l5 = models.TextField(null=True, blank=True)
    dim12 = models.TextField(null=True, blank=True)
    d12_l1 = models.TextField(null=True, blank=True)
    d12_l2 = models.TextField(null=True, blank=True)
    d12_l3 = models.TextField(null=True, blank=True)
    d12_l4 = models.TextField(null=True, blank=True)
    d12_l5 = models.TextField(null=True, blank=True)
    dim13 = models.TextField(null=True, blank=True)
    d13_l1 = models.TextField(null=True, blank=True)
    d13_l2 = models.TextField(null=True, blank=True)
    d13_l3 = models.TextField(null=True, blank=True)
    d13_l4 = models.TextField(null=True, blank=True)
    d13_l5 = models.TextField(null=True, blank=True)
    dim14 = models.TextField(null=True, blank=True)
    d14_l1 = models.TextField(null=True, blank=True)
    d14_l2 = models.TextField(null=True, blank=True)
    d14_l3 = models.TextField(null=True, blank=True)
    d14_l4 = models.TextField(null=True, blank=True)
    d14_l5 = models.TextField(null=True, blank=True)
    dim15 = models.TextField(null=True, blank=True)
    d15_l1 = models.TextField(null=True, blank=True)
    d15_l2 = models.TextField(null=True, blank=True)
    d15_l3 = models.TextField(null=True, blank=True)
    d15_l4 = models.TextField(null=True, blank=True)
    d15_l5 = models.TextField(null=True, blank=True)


class TagDicts(models.Model):
    dict_filename = models.CharField(max_length=100)
    ngram = models.CharField(max_length=255)
    dim1 = models.TextField(null=True, blank=True)
    d1_l1 = models.TextField(null=True, blank=True)
    d1_l2 = models.TextField(null=True, blank=True)
    d1_l3 = models.TextField(null=True, blank=True)
    d1_l4 = models.TextField(null=True, blank=True)
    d1_l5 = models.TextField(null=True, blank=True)
    dim2 = models.TextField(null=True, blank=True)
    d2_l1 = models.TextField(null=True, blank=True)
    d2_l2 = models.TextField(null=True, blank=True)
    d2_l3 = models.TextField(null=True, blank=True)
    d2_l4 = models.TextField(null=True, blank=True)
    d2_l5 = models.TextField(null=True, blank=True)
    dim3 = models.TextField(null=True, blank=True)
    d3_l1 = models.TextField(null=True, blank=True)
    d3_l2 = models.TextField(null=True, blank=True)
    d3_l3 = models.TextField(null=True, blank=True)
    d3_l4 = models.TextField(null=True, blank=True)
    d3_l5 = models.TextField(null=True, blank=True)
    dim4 = models.TextField(null=True, blank=True)
    d4_l1 = models.TextField(null=True, blank=True)
    d4_l2 = models.TextField(null=True, blank=True)
    d4_l3 = models.TextField(null=True, blank=True)
    d4_l4 = models.TextField(null=True, blank=True)
    d4_l5 = models.TextField(null=True, blank=True)
    dim5 = models.TextField(null=True, blank=True)
    d5_l1 = models.TextField(null=True, blank=True)
    d5_l2 = models.TextField(null=True, blank=True)
    d5_l3 = models.TextField(null=True, blank=True)
    d5_l4 = models.TextField(null=True, blank=True)
    d5_l5 = models.TextField(null=True, blank=True)
    dim6 = models.TextField(null=True, blank=True)
    d6_l1 = models.TextField(null=True, blank=True)
    d6_l2 = models.TextField(null=True, blank=True)
    d6_l3 = models.TextField(null=True, blank=True)
    d6_l4 = models.TextField(null=True, blank=True)
    d6_l5 = models.TextField(null=True, blank=True)
    dim7 = models.TextField(null=True, blank=True)
    d7_l1 = models.TextField(null=True, blank=True)
    d7_l2 = models.TextField(null=True, blank=True)
    d7_l3 = models.TextField(null=True, blank=True)
    d7_l4 = models.TextField(null=True, blank=True)
    d7_l5 = models.TextField(null=True, blank=True)
    dim8 = models.TextField(null=True, blank=True)
    d8_l1 = models.TextField(null=True, blank=True)
    d8_l2 = models.TextField(null=True, blank=True)
    d8_l3 = models.TextField(null=True, blank=True)
    d8_l4 = models.TextField(null=True, blank=True)
    d8_l5 = models.TextField(null=True, blank=True)
    dim9 = models.TextField(null=True, blank=True)
    d9_l1 = models.TextField(null=True, blank=True)
    d9_l2 = models.TextField(null=True, blank=True)
    d9_l3 = models.TextField(null=True, blank=True)
    d9_l4 = models.TextField(null=True, blank=True)
    d9_l5 = models.TextField(null=True, blank=True)
    dim10 = models.TextField(null=True, blank=True)
    d10_l1 = models.TextField(null=True, blank=True)
    d10_l2 = models.TextField(null=True, blank=True)
    d10_l3 = models.TextField(null=True, blank=True)
    d10_l4 = models.TextField(null=True, blank=True)
    d10_l5 = models.TextField(null=True, blank=True)
    dim11 = models.TextField(null=True, blank=True)
    d11_l1 = models.TextField(null=True, blank=True)
    d11_l2 = models.TextField(null=True, blank=True)
    d11_l3 = models.TextField(null=True, blank=True)
    d11_l4 = models.TextField(null=True, blank=True)
    d11_l5 = models.TextField(null=True, blank=True)
    dim12 = models.TextField(null=True, blank=True)
    d12_l1 = models.TextField(null=True, blank=True)
    d12_l2 = models.TextField(null=True, blank=True)
    d12_l3 = models.TextField(null=True, blank=True)
    d12_l4 = models.TextField(null=True, blank=True)
    d12_l5 = models.TextField(null=True, blank=True)
    dim13 = models.TextField(null=True, blank=True)
    d13_l1 = models.TextField(null=True, blank=True)
    d13_l2 = models.TextField(null=True, blank=True)
    d13_l3 = models.TextField(null=True, blank=True)
    d13_l4 = models.TextField(null=True, blank=True)
    d13_l5 = models.TextField(null=True, blank=True)
    dim14 = models.TextField(null=True, blank=True)
    d14_l1 = models.TextField(null=True, blank=True)
    d14_l2 = models.TextField(null=True, blank=True)
    d14_l3 = models.TextField(null=True, blank=True)
    d14_l4 = models.TextField(null=True, blank=True)
    d14_l5 = models.TextField(null=True, blank=True)
    dim15 = models.TextField(null=True, blank=True)
    d15_l1 = models.TextField(null=True, blank=True)
    d15_l2 = models.TextField(null=True, blank=True)
    d15_l3 = models.TextField(null=True, blank=True)
    d15_l4 = models.TextField(null=True, blank=True)
    d15_l5 = models.TextField(null=True, blank=True)


class Social(models.Model):
    dataset_filename = models.TextField(null=False)
    rid = models.CharField(max_length=255, null=False)
    rTitle = models.TextField(null=True, blank=True)
    rUser = models.TextField(null=True, blank=True)
    rText = models.TextField(null=True, blank=True)
    rURL = models.TextField(null=True, blank=True)
    MEDIA_PROVIDER = models.TextField(null=True, blank=True)
    rDate = UnixDateTimeField(null=True, blank=True)
    rDate2 = models.DateField(null=True, blank=True)
    VIEW_COUNT = models.IntegerField(null=True, blank=True)
    COMMENT_COUNT = models.IntegerField(null=True, blank=True)
    UNIQUE_COMMENTERS = models.IntegerField(null=True, blank=True)
    ENGAGEMENT = models.IntegerField(null=True, blank=True)
    LINKS_AND_VOTES = models.IntegerField(null=True, blank=True)
    INBOUND_LINKS = models.IntegerField(null=True, blank=True)
    FORUM_THREAD_SIZE = models.IntegerField(null=True, blank=True)
    FOLLOWING = models.IntegerField(null=True, blank=True)
    FOLLOWERS = models.IntegerField(null=True, blank=True)
    UPDATES = models.IntegerField(null=True, blank=True)
    BLOG_POST_SENTIMENT = models.CharField(max_length=45, null=True, blank=True)


class DataDictMap(models.Model):
    dataset_filename = models.TextField(null=False)
    dict_filename = models.TextField(null=False)


class TaggedData(models.Model):
    dataset_filename = models.TextField(null=False)
    rid = models.CharField(max_length=255, null=False)
    dim1 = models.TextField(null=True, blank=True)
    d1_l1 = models.TextField(null=True, blank=True)
    d1_l2 = models.TextField(null=True, blank=True)
    d1_l3 = models.TextField(null=True, blank=True)
    d1_l4 = models.TextField(null=True, blank=True)
    d1_l5 = models.TextField(null=True, blank=True)
    dim2 = models.TextField(null=True, blank=True)
    d2_l1 = models.TextField(null=True, blank=True)
    d2_l2 = models.TextField(null=True, blank=True)
    d2_l3 = models.TextField(null=True, blank=True)
    d2_l4 = models.TextField(null=True, blank=True)
    d2_l5 = models.TextField(null=True, blank=True)
    dim3 = models.TextField(null=True, blank=True)
    d3_l1 = models.TextField(null=True, blank=True)
    d3_l2 = models.TextField(null=True, blank=True)
    d3_l3 = models.TextField(null=True, blank=True)
    d3_l4 = models.TextField(null=True, blank=True)
    d3_l5 = models.TextField(null=True, blank=True)
    dim4 = models.TextField(null=True, blank=True)
    d4_l1 = models.TextField(null=True, blank=True)
    d4_l2 = models.TextField(null=True, blank=True)
    d4_l3 = models.TextField(null=True, blank=True)
    d4_l4 = models.TextField(null=True, blank=True)
    d4_l5 = models.TextField(null=True, blank=True)
    dim5 = models.TextField(null=True, blank=True)
    d5_l1 = models.TextField(null=True, blank=True)
    d5_l2 = models.TextField(null=True, blank=True)
    d5_l3 = models.TextField(null=True, blank=True)
    d5_l4 = models.TextField(null=True, blank=True)
    d5_l5 = models.TextField(null=True, blank=True)
    dim6 = models.TextField(null=True, blank=True)
    d6_l1 = models.TextField(null=True, blank=True)
    d6_l2 = models.TextField(null=True, blank=True)
    d6_l3 = models.TextField(null=True, blank=True)
    d6_l4 = models.TextField(null=True, blank=True)
    d6_l5 = models.TextField(null=True, blank=True)
    dim7 = models.TextField(null=True, blank=True)
    d7_l1 = models.TextField(null=True, blank=True)
    d7_l2 = models.TextField(null=True, blank=True)
    d7_l3 = models.TextField(null=True, blank=True)
    d7_l4 = models.TextField(null=True, blank=True)
    d7_l5 = models.TextField(null=True, blank=True)
    dim8 = models.TextField(null=True, blank=True)
    d8_l1 = models.TextField(null=True, blank=True)
    d8_l2 = models.TextField(null=True, blank=True)
    d8_l3 = models.TextField(null=True, blank=True)
    d8_l4 = models.TextField(null=True, blank=True)
    d8_l5 = models.TextField(null=True, blank=True)
    dim9 = models.TextField(null=True, blank=True)
    d9_l1 = models.TextField(null=True, blank=True)
    d9_l2 = models.TextField(null=True, blank=True)
    d9_l3 = models.TextField(null=True, blank=True)
    d9_l4 = models.TextField(null=True, blank=True)
    d9_l5 = models.TextField(null=True, blank=True)
    dim10 = models.TextField(null=True, blank=True)
    d10_l1 = models.TextField(null=True, blank=True)
    d10_l2 = models.TextField(null=True, blank=True)
    d10_l3 = models.TextField(null=True, blank=True)
    d10_l4 = models.TextField(null=True, blank=True)
    d10_l5 = models.TextField(null=True, blank=True)
    dim11 = models.TextField(null=True, blank=True)
    d11_l1 = models.TextField(null=True, blank=True)
    d11_l2 = models.TextField(null=True, blank=True)
    d11_l3 = models.TextField(null=True, blank=True)
    d11_l4 = models.TextField(null=True, blank=True)
    d11_l5 = models.TextField(null=True, blank=True)
    dim12 = models.TextField(null=True, blank=True)
    d12_l1 = models.TextField(null=True, blank=True)
    d12_l2 = models.TextField(null=True, blank=True)
    d12_l3 = models.TextField(null=True, blank=True)
    d12_l4 = models.TextField(null=True, blank=True)
    d12_l5 = models.TextField(null=True, blank=True)
    dim13 = models.TextField(null=True, blank=True)
    d13_l1 = models.TextField(null=True, blank=True)
    d13_l2 = models.TextField(null=True, blank=True)
    d13_l3 = models.TextField(null=True, blank=True)
    d13_l4 = models.TextField(null=True, blank=True)
    d13_l5 = models.TextField(null=True, blank=True)
    dim14 = models.TextField(null=True, blank=True)
    d14_l1 = models.TextField(null=True, blank=True)
    d14_l2 = models.TextField(null=True, blank=True)
    d14_l3 = models.TextField(null=True, blank=True)
    d14_l4 = models.TextField(null=True, blank=True)
    d14_l5 = models.TextField(null=True, blank=True)
    dim15 = models.TextField(null=True, blank=True)
    d15_l1 = models.TextField(null=True, blank=True)
    d15_l2 = models.TextField(null=True, blank=True)
    d15_l3 = models.TextField(null=True, blank=True)
    d15_l4 = models.TextField(null=True, blank=True)
    d15_l5 = models.TextField(null=True, blank=True)
